name: Deploy about.html to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "src/templates/about.html"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create docs folder and copy about.html
        run: |
          mkdir -p docs
          cp src/templates/about.html docs/

      - name: Commit and push docs folder
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/about.html
          git commit -m "Update about.html for GitHub Pages" || echo "No changes to commit"
          git push

